### PR TITLE
New fingerprint panel

### PR DESCRIPTION
**Pull request by bellegarde-c**
This is a new fingerprint panel for Droidian.

I reverted back previous fingerprint commits instead of removing them.

[fingerprint.webm](https://github.com/droidian/gnome-control-center/assets/57196916/4f830a9d-ab9e-401e-9769-568c9c6ae8b8)

### CODE REVIEW

**Comment by mathew-dennis** [comment]
As a suggestion, may be it would be good to rename "remove fingerprints" to "enrolled fingerprints"

**Comment by g7** [comment]
Thank you! I like it already and it's a decisive improvement with what we had before  :D

**Comment by g7** [comment]
Thank you! I like it already and it's a decisive improvement with what we had before  :D 

Just food for thought: what about showing the big fingerprint icon only during enrollment? And maybe then there is space for showing the fingerprint list in its entirety in the main page. 
But on the flip side we lose the simplicity of this current panel.

This is just to spawn a discussion, personally I'm happy with how it is right now as well! :)

**Comment by mathew-dennis** [comment]
If I may, considering the primary reason for people to visit this page would be to enroll a new finger print , so showing the enrolled fingerprints in a drop down menu (what this pr currently has) can be considered as a good idea...also maybe making the fingerprint icon smallar would be good too...ps : this Is just my thought😀

**Comment by bellegarde-c** [comment]
Just resized the fingerprint icon to 200x200. Looks better like this.

**Comment by g7** [comment]
Thanks, merging

**Pull request merged**
