### PR TITLE
Add support for Mobile Power Saver, Battery Input Manager and Mobile Settings

### PR DESCRIPTION
**Pull request by bellegarde-c**
Patch works even if packages are not installed.

### CODE REVIEW

**Comment by bellegarde-c** [comment]
Once this is merged, we need to communicate towards device maintainers:

* For double tap support, custom handling via startup script should be removed and mobile-settings needs to be added to dependencies and this override file is needed:

```
# cat 10_mobile_settings.gschema.override 
[org.droidian.MobileSettings]
touchpanel-double-tap-available = true
```

* For Battery Input Manager support, checking device is handled by https://gitlab.gnome.org/gnumdk/battery-input-manager/-/blob/main/data/devices.json

**Comment by g7** [comment]
Thanks a lot! I think we can add mobile-settings to the metapackages so that everyone gets it (it will be useful for a lot of things).

For Battery Input Manager, I would keep it outside for now (or perhaps we can install it by default but keeping it disabled) - I'm worried that on some devices it might actually be dangerous (see https://xdaforums.com/t/rom-official-arrowos-11-0-android-11-0-vayu-bhima.4267263/page-14#post-85119331 for example).

What do you think?

**Comment by g7** [comment]
Added mobile-settings for everyone in the metapackages, let's keep battery input manager outside for now.

Thanks!

**Comment by bellegarde-c** [comment]
IMO, battery-input-manager should be a device maintainer choice:
* XDA issue looks like a really good reason
* Some check needs to be done for input suspend support

**Pull request merged**
