### PR TITLE
GNOME 47 upgrade

### PR DESCRIPTION
**Pull request by g7**
Most of the adaptation work for our panels is in the "merge commit".

Everything looks fine to me, Waydroid panel has been untouched so I hope it won't conflict with your work @bellegarde-c  ;)

### CODE REVIEW

**Comment by bellegarde-c** [comment]
Looks good to me but shouldn't we just apply droidian commits on top of GNOME main ? This will keep droidian commits on top. What do you think ?

**Comment by g7** [comment]
Thanks for checking - yeah adding commits on top is cleaner but will mean rewriting the git history every time and force-pushing

I'm good with either methods (as the buildd doesn't really care), I think we should just agree on what to do

**Comment by g7** [comment]
...or we  can move to branches like we do e.g. for gnome-clocks, so every major release has its own branch and we inject that in the snapshot... we preserve history while we're able to "restart from scratch" at every release

**Comment by g7** [comment]
Cleaned up and rebased in [feature/next/upgrade-47-rebase](https://github.com/droidian/gnome-control-center/tree/feature/next/upgrade-47-rebase)

Closing this

**Pull request closed without merging**
