### PR TITLE
panels: Rename mtp panel to usb panel

### PR DESCRIPTION
**Pull request by bellegarde-c**
- Rework interface
- Replace system() by DBus calls
- Respect gnome-control-center coding style

### CODE REVIEW

**Comment by bellegarde-c** [comment]
I choosed to rename the panel from MTP to USB (as it is configuring USB port, not just MTP).

One more argument toward this change: People know what USB is, not MTP.

usb

**Comment by bellegarde-c** [comment]
Looking at mtp-configfs script, I guess we can remove the pooling code.

Move mtp-configfs to a oneshot systemd service and remove loop.

Add polkit rules allowing droidian user to start mtp-configfs.

Via DBus, start mtp-configfs as soon user update settings in gnome-control-center.

@g7 What do you think ?

**Comment by g7** [comment]
Thanks for looking at this! Looks great, and the rename makes total sense. Also thanks for moving to DBus.

I didn't work at the original mtp-server implementation, so I might miss something... but I wonder if we should simply make the `mtp-server` systemd service a multiple-instance service.

Something

**Comment by g7** [comment]
(sorry, fat fingered the Close button)

Thanks for looking at this! It totally makes sense to me, including the rename (also thanks for properly move to DBus).

I didn't work at the original implementation, so I might miss something... but I think we might make the `mtp-configfs` systemd service a multi-instance service, and use that in place of the `mtp-configfs.conf` configuration file. As we're interested on USBMODE= anyway.

Something like `mtp-configfs@mtp`, `mtp-configfs@rndis` etc. This way we can avoid modifying the configuration file at all (which, to be honest, I don't like much), and do everything via systemd (on switch, disable `@mtp`, enable `@rndis`).

I can try looking at it. What do you think? Does it make sense to you?

**Comment by bellegarde-c** [comment]
Yes make sense and is a lot better than current version code. Will simplify a lot this panel.

**Comment by bellegarde-c** [comment]
Just found the commit, will port this pull request to this new service file tomorrow.

**Comment by g7** [comment]
Thanks, yes, related Pull Request: droidian/mtp-server#4

**Comment by bellegarde-c** [comment]
Sadly, org.freedesktop.systemd1.manage-unit-files does not pass details to polkit and we can't filter on mtp-configfs@.* for polkit rule. 

So looks like using systemd multi-instance will not work without giving droidian user full access to system services :-(

**Comment by g7** [comment]
ah, unfortunate. I guess we can use two different services then: mtp-configfs-rndis and mtp-configfs-mtp, what do you think?

**Comment by bellegarde-c** [comment]
Should not fix the issue, gnome-control-center will be unable to enable one or other service.

BTW, this is working:
```
[Unit]
Description=usb state change: to %i
Requires=lxc@android.service
After=phosh.service

[Service]
Type=oneshot
ExecStartPre=-chown droidian:droidian /dev/mtp_usb
ExecStartPre=-rm -f /etc/systemd/system/graphical.target.wants/mtp-configfs@none.service
ExecStartPre=-rm -f /etc/systemd/system/graphical.target.wants/mtp-configfs@mtp.service
ExecStartPre=-rm -f /etc/systemd/system/graphical.target.wants/mtp-configfs@rndis.service
ExecStartPre=-ln -sf /usr/lib/systemd/system/mtp-configfs@.service /etc/systemd/system/graphical.target.wants/mtp-configfs@%i.service
ExecStart=/usr/sbin/mtp-configfs %i

[Install]
WantedBy=graphical.target
```

**Comment by bellegarde-c** [comment]
Cool, it works as expected.

**Comment by bellegarde-c** [comment]
Patch updated to work with you mtp-server branch and https://github.com/droidian/gnome-control-center/pull/4#issuecomment-2220403122

**Comment by mathew-dennis** [comment]
After=phosh.service
This may be a problem for cutie and possibly plasma?

**Comment by bellegarde-c** [comment]
> After=phosh.service This may be a problem for cutie and possibly plasma?

It's not **Requires** so I guess no. But it will do nothing on plasma/cutie.

**Comment by erikinkinen** [comment]
> > After=phosh.service This may be a problem for cutie and possibly plasma?
> 
> It's not **Requires** so I guess no. But it will do nothing on plasma/cutie.

Why do we need to wait for phosh.service in the first place?

**Comment by bellegarde-c** [comment]
> Why do we need to wait for phosh.service in the first place?

Excellent question :)

**Comment by g7** [comment]
> Should not fix the issue, gnome-control-center will be unable to enable one or other service.

ah got it. Thought we lose only the multi-instance info, but we lose everything instead :(

> BTW, this is working:

looks a bit cursed :sweat_smile: but I'll take it, thanks! I have no better suggestion

> Why do we need to wait for phosh.service in the first place?

I have no clue, but I suppose the intention was to have it start somewhat late in the boot process to avoid vendor init scripts in the android side resetting the usb state.

I will change that to `android_boot_completed.service` that should work as well, and will also work with other DEs.

**Comment by g7** [comment]
Thanks!

**Pull request merged**
